name: MongoDB Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
    - uses: actions/checkout@v2

    - name: Setup MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with: 
        mongodb-version: 4.2.8
        mongodb-replica-set: test-py
    - name: Test the MongoDB with pymongo
      run: python test_mongo.py
